# Generated by Django 2.2.4 on 2019-12-17 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0011_merge_20190731_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
