# Generated by Django 2.2.4 on 2019-12-17 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0013_remove_target_color'),
        ('tom_targets', '0015_auto_20190923_2233'),
    ]

    operations = [
    ]
