# Generated by Django 2.2.4 on 2020-05-26 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tom_targets', '0016_merge_20191217_1953'),
        ('tom_targets', '0017_auto_20200130_2350'),
    ]

    operations = [
    ]
